version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: adwords
        identifier: raw_gz_adwords
        description: adwords advertising campaign
        columns:
          - name: date_date
            description: date of campaign
          - name: paid_source
            description: the marketing platform where paid campaign traffic originated 
          - name: campaign_key
            description: primary key
            tests:
              - not_null
          - name: campaign_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the campaign
          - name: impression
            description: the number of times ad was displayed to a user
          - name: click
            description: the number of times users clicked on an ad 
      - name: bing
        identifier: raw_gz_bing
        description: bing advertising campaign
        columns:
          - name: date_date
            description: date of campaign
          - name: paid_source
            description: the marketing platform where paid campaign traffic originated 
          - name: campaign_key
            description: primary key
            tests:
              - not_null
          - name: campaign_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the campaign
          - name: impression
            description: the number of times ad was displayed to a user
          - name: click
            description: the number of times users clicked on an ad
      - name: criteo
        identifier: raw_gz_criteo
        description: criteo advertising campaign
        columns:
          - name: date_date
            description: date of campaign
          - name: paid_source
            description: the marketing platform where paid campaign traffic originated 
          - name: campaign_key
            description: primary key
            tests:
              - not_null
          - name: campaign_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the campaign
          - name: impression
            description: the number of times ad was displayed to a user
          - name: click
            description: the number of times users clicked on an ad
      - name: facebook
        identifier: raw_gz_facebook
        description: facebook advertising campaign
        columns:
          - name: date_date
            description: date of campaign
          - name: paid_source
            description: the marketing platform where paid campaign traffic originated 
          - name: campaign_key
            description: primary key
            tests:
              - not_null
          - name: campaign_name
            description: name of the campaign
          - name: ads_cost
            description: cost of the campaign
          - name: impression
            description: the number of times ad was displayed to a user
          - name: click
            description: the number of times users clicked on an ad
      - name: sales
        identifier: raw_gz_sales
        description: sales of products
        #freshness test:
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
           warn_after: {count: 90, period: day}
        
        columns:
          - name: date_date
            description: date of purchase
          - name: orders_id
            description: id of order 
          - name: products_id
            description: id of the product purchased
          - name: revenue
            description: the revenue generated with the order
          - name: quantity
            description: the number of products 
      - name: product
        identifier: raw_gz_product
        description: stock of products
        columns:
          - name: products_id
            description: Primary key for the product table
            tests:
              - unique
              - not_null
          - name: purchSE_PRICE
            description: the purchase price of the product
      - name: ship
        identifier: raw_gz_ship
        description: shipping information
        columns:
          - name: orders_id
            description: Primary key for the ship table
            tests:
              - unique
              - not_null
          - name: shipping_fee
            description: the shipping fee we charged the user
          - name: log_cost
            description: total logistic costs
          - name: ship_cost
            description: the overall shipping costs
models:
      # Intermediate #
      - name: int_sales_margin
        description: margin calculation per order
        columns:
          - name: orders_id
            description: orders key
            tests:
              - not_null
          - name: products_id
            description: products key
            tests:
              - not_null
          - name: margin
            description: Margin = Revenue - Purchase_cost
            tests:
              - not_null
          - name: Purchase_cost
            description: Purchase_cost = Quantity * Purchase_price
            tests:
              - not_null
          - name: date_date
            description: date of the order
            tests:
              - not_null
          - name: revenue
            description: sum of revenue per order
            tests:
              - not_null
          - name: quantity
            description: sum of quantity per order
            tests:
              - not_null    
        tests:
          - unique:
              column_name: "(orders_id || '-' || products_id)"
      - name: int_orders_margin
        description: margin calculation per order
        columns:
          - name: orders_id
            description: primary key
            tests:
              - not_null
          - name: date_date
            description: date of the order
            tests:
              - not_null
          - name: revenue
            description: sum of revenue per order
            tests:
              - not_null
          - name: quantity
            description: sum quantity per order
            tests:
              - not_null
          - name: purchase_cost
            description: sum of purchase cost
            tests:
              - not_null
        tests:
          - unique:
              column_name: "(orders_id)"
      - name: int_orders_operational
        description: operational margin calculation per order
        columns:
          - name: orders_id
            description: primary key
            tests:
              - not_null
          - name: date_date
            description: date of the order
            tests:
              - not_null
          - name: operational_margin
            description: operational_margin = margin + shipping_fee - log_cost - ship_cost
            tests:
              - not_null
          - name: quantity
            description: sum of quantity per order
            tests:
              - not_null
          - name: revenue
            description: sum of revenue per order
            tests:
              - not_null
          - name: purchase_cost
            description: purchase_cost = quantity * purchase_price
            tests:
              - not_null
          - name: margin
            description: margin = revenue - purchase_cost
            tests:
              - not_null
          - name: shipping_fee
            description: the price the customer pays for shipping
            tests:
              - not_null
          - name: log_cost
            description: the cost of preparing the parcel in the distribution centre/warehouse
            tests:
              - not_null
          - name: ship_cost
            description: shipping cost paid by Greenweez to the carrier/logistics provider
            tests:
              - not_null             
        tests:
          - unique:
              column_name: "(orders_id)"
      
      # mart #
      - name: finance_campaigns_day
        description: all KPIs
        columns:
          - name: ads_margin
            description: operational_margin - ads_cost
            
          