version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of products
      - name: product
        identifier: raw_gz_product
        description: stock of products
      - name: ship
        identifier: raw_gz_ship
        description: shipping information